project:
  type: website
  output-dir: ../docs


website:
  title: "Vicsek and Obstacles"
  sidebar:
    smooth-scroll: true
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - index.qmd



format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 305px
    toc: true
    number-chapters: true
    number-sections: true