project:
  type: website
  output-dir: ../docs

website:
  title: "Vicsek and Obstacles"
  # sidebar:
  #   smooth-scroll: true
  #   style: "docked"
  #   search: false
  #   collapse-level: 1
  #   contents:
  #     - index.qmd

format:
  html:
    theme: cosmo
    # grid:
      # sidebar-width: 305px
    toc: true
    number-chapters: false  
    number-sections: false
    css: styles.css